name = "fiddletwo/parkar"
version = "0.1.0"
authors = ["fiddletwo"]
repository = "https://github.com/fiddletwo/parkar"
license = "MIT"

[target]
environment = "roblox"

[place]
shared = "game.ReplicatedStorage.packages"
server = "game.ServerScriptService.packages"

[indices]
default = "https://github.com/pesde-pkg/index"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[scripts]
roblox_sync_config_generator = ".pesde/scripts_rojo/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts_rojo/sourcemap_generator.luau"

[dev_dependencies]
scripts_rojo = { name = "pesde/scripts_rojo", version = "^0.2.0", target = "lune" }

[engines]
pesde = "^0.7.0"
lune = "^0.10.2"

[dependencies]
jabby = { wally = "alicesaidhi/jabby", version = "^0.6.1" }
jecs = { wally = "ukendio/jecs", version = "^0.11.0" }
jecs-utils = { wally = "pepeeltoro41/jecs-utils", version = "^1.4.4" }
planck = { wally = "yetanotherclown/planck", version = "^0.3.0-rc.2" }
planck-jabby = { wally = "yetanotherclown/planck-jabby", version = "^0.3.0-rc.2" }
planck-runservice = { wally = "yetanotherclown/planck-runservice", version = "^0.3.0-rc.2" }
vide = { wally = "centau/vide", version = "^0.4.1" }
replecs = { wally = "pepeeltoro41/replecs", version = "^0.4.0-rc.3" }

[overrides]
"jabby>vide" = "vide"
"planck-jabby>jabby" = "jabby"
"replecs>jecs,jecs-spring>jecs" = "jecs"
